using Google.Cloud.Firestore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelpForHireWebApi.Models
{
    /// <summary>
    /// This model holds information relevant to the history
    /// of a user. This class is used by both employers and
    /// workers
    /// </summary>
    [FirestoreData]
    public class History
    {
        /// <summary>
        /// ID for each history entry in the database.
        /// 
        /// Is auto-generated by Firestore
        /// </summary>
        [Required]
        public string HistoryId { get; set; }

        /// <summary>
        /// Description of the history entry for a user.
        /// 
        /// An example is: "You registered on 2021/01/01"
        /// </summary>
        [Required]
        [FirestoreProperty]
        [StringLength(256)]
        public string Description { get; set; }

        /// <summary>
        /// Reference to a user which this history entry belongs to.
        /// 
        /// Works for both employers and workers as they both share
        /// the UserId property
        /// </summary>
        [Required]
        [FirestoreProperty]
        [StringLength(13, MinimumLength = 13)]
        public string UserId { get; set; }
    }
}
