using Google.Cloud.Firestore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelpForHireWebApi.Models
{
    /// <summary>
    /// This model class holds information relevant to invites
    /// sent by employers to workers
    /// </summary>
    [FirestoreData]
    public class Invite
    {
        /// <summary>
        /// The unique ID which gets auto-generated by Firestore
        /// for each invite
        /// </summary>
        [Required]
        public string InviteId { get; set; }

        /// <summary>
        /// The current status of the invite.
        /// 
        /// An invite may be accepted, declined or pending
        /// </summary>
        [Required]
        [FirestoreProperty]
        [StringLength(256)]
        public string Status { get; set; }

        /// <summary>
        /// The employer to which this invite belongs
        /// </summary>
        [Required]
        [FirestoreProperty]
        [StringLength(13, MinimumLength = 13)]
        public string EmployerId { get; set; }

        /// <summary>
        /// The worker to which this invite was sent
        /// </summary>
        [Required]
        [FirestoreProperty]
        [StringLength(13, MinimumLength = 13)]
        public string WorkerId { get; set; }
    }
}
