using Google.Cloud.Firestore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HelpForHireWebApi.Models
{
    /// <summary>
    /// This model holds information relevant to the jobs
    /// which a worker can perform.
    /// 
    /// This class is also used in the Flutter application
    /// to sort worker profiles by job type
    /// </summary>
    [FirestoreData]
    public class Job
    {
        /// <summary>
        /// The unique ID which gets auto-generated by Firestore for
        /// each job
        /// </summary>
        [Required]
        public string JobId { get; set; }

        /// <summary>
        /// The job title.
        /// 
        /// Such as "House Cleaner", "Painter" or "Gardener"
        /// </summary>
        [Required]
        [FirestoreProperty]
        public string Title { get; set; }
    }
}
